name: Deploy to ECS (Dev)

on:
  push:
    branches: [ "main" ] 

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}                 
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}         
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}                
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}               
  ECS_TASK_DEFINITION: ${{ secrets.ECS_TASK_DEFINITION }} 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          # Build with ECR repository tag
          docker build -t $ECR_REPOSITORY:dev .
          # Tag with Git SHA for traceability
          docker tag $ECR_REPOSITORY:dev $ECR_REPOSITORY:$GITHUB_SHA
          # Push both tags to ECR
          docker push $ECR_REPOSITORY:dev
          docker push $ECR_REPOSITORY:$GITHUB_SHA

      - name: Download existing task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition $ECS_TASK_DEFINITION \
            --query 'taskDefinition' > task-definition.json

      - name: Update task definition with new image
        run: |
          # Use jq to update the image URL
          jq '.containerDefinitions[0].image = "'"$ECR_REPOSITORY"':dev"' task-definition.json > updated-task-definition.json
          # Print for debugging
          cat updated-task-definition.json

      - name: Register new task definition revision
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://updated-task-definition.json

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --task-definition $ECS_TASK_DEFINITION \
            --force-new-deployment

      - name: Verify deployment status
        run: |
          aws ecs wait services-stable \
            --cluster $ECS_CLUSTER \
            --services $ECS_SERVICE